### ISSUE TITLE
Message Spam

### ISSUE THREAD

**Issue by iSkyify** [xFyreWolfx/WarCrates#1]
Is there a way to limit the amount of opened chests message? Would love it if it only showed "20 crates left" "10 crates left" "5 crates left" instead of a message for everytime a player opened the chest

**Comment by xFyreWolfx** [comment]
Thanks for the suggestion! This has been implemented in the latest commit, plugin version 1.0.3. Some users may need to regenerate their config.yml file in order to see the changes.
